publish_imu: &publish_imu
  imu: true

limits: &limits
  acceleration:
    linear: 5
    angular: 5
  twist:
    linear: 2
    angular: 2

imu_covariances: &imu_covariances
  accelerometer: 0.01
  gyro: 0.1
  magnetometer: 0.002

oswin: &oswin
  imu_covariances: *imu_covariances
  state:
    pose:
      position:
        x: 0
        y: 0
    twist:
      linear: 0
      angular: 0
  limits: *limits
  publishers: *publish_imu

worlds:
  imu_test:
    turtles:
      oswin: *oswin
