publish_imu: &publish_pose_and_lidar
  pose: true
  lidar: true

limits: &limits
  acceleration:
    linear: 5
    angular: 5
  twist:
    linear: 2
    angular: 2

lidar_options: &lidar_options
  angle_width: 3.1415926 # End angle - start angle. Rad
  range: 10
  angular_resolution: 0.01 # Rad

obstacles: &obstacles
  - type: polygon
    points: [[1, 1], [1, 3], [3, 3], [3, 1]]
  - type: polygon
    points: [[-2, 2], [-1, 3], [-3, 4], [-4, 1]]

oswin: &oswin
  lidar: *lidar_options
  lidar_painter:
    visualization_ratio: 5
  state:
    pose:
      position:
        x: -5
        y: 0
    twist:
      linear: 0
      angular: 0
  limits: *limits
  publishers: *publish_pose_and_lidar

worlds:
  basic_mapping:
    turtles:
      oswin: *oswin
    obstacles: *obstacles
